
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yaml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--log.level=debug"  # Enable debug logging
      - "--web.enable-admin-api"
      - "--web.enable-remote-write-receiver"
